### ISSUE TITLE
When a folder of previously tracked `__init__.py` file gets deleted, the hook crashes 

### ISSUE THREAD

**Issue by lk16** [lk16/detect-missing-init#1]
See below stacktrace:

```
Traceback (most recent call last):
  File "/home/luuk/.cache/pre-commit/repo9weblqgp/py_env-python3.10/bin/detect-missing-init", line 8, in <module>
    sys.exit(main())
  File "/home/luuk/.cache/pre-commit/repo9weblqgp/py_env-python3.10/lib/python3.10/site-packages/hook/detect_missing_init.py", line 110, in main
    missing_init_files = find_missing_init_files(folders)
  File "/home/luuk/.cache/pre-commit/repo9weblqgp/py_env-python3.10/lib/python3.10/site-packages/hook/detect_missing_init.py", line 49, in find_missing_init_files
    if not init_path.exists() and contains_python_file(folder):
  File "/home/luuk/.cache/pre-commit/repo9weblqgp/py_env-python3.10/lib/python3.10/site-packages/hook/detect_missing_init.py", line 36, in contains_python_file
    for file in folder.iterdir():
  File "/home/luuk/.pyenv/versions/3.10.2/lib/python3.10/pathlib.py", line 1015, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [Errno 2] No such file or directory: 'tests/parser'
```

**Comment by lk16** [comment]
Fixed in release [v0.1.4](https://github.com/lk16/detect-missing-init/tree/v0.1.4).
