### ISSUE TITLE
Hook fails with PermissionError for not accessible files 

### ISSUE THREAD

**Issue by paveldedik** [lk16/detect-missing-init#4]
Hi,

when you create a directory in your repository, with permissions e.g. `chmod 000`, the extension fails with the following error:

```
Traceback (most recent call last):
  File "/home/pavel/.cache/pre-commit/repoxamyetpl/py_env-python3.10/bin/detect-missing-init", line 8, in <module>
    sys.exit(main())
  File "/home/pavel/.cache/pre-commit/repoxamyetpl/py_env-python3.10/lib/python3.10/site-packages/hook/detect_missing_init.py", line 136, in main
    missing_init_files = find_missing_init_files(
  File "/home/pavel/.cache/pre-commit/repoxamyetpl/py_env-python3.10/lib/python3.10/site-packages/hook/detect_missing_init.py", line 73, in find_missing_init_files
    contains_python_file(folder),
  File "/home/pavel/.cache/pre-commit/repoxamyetpl/py_env-python3.10/lib/python3.10/site-packages/hook/detect_missing_init.py", line 58, in contains_python_file
    if file.is_dir() and contains_python_file(file):
  File "/home/pavel/.cache/pre-commit/repoxamyetpl/py_env-python3.10/lib/python3.10/site-packages/hook/detect_missing_init.py", line 55, in contains_python_file
    for file in folder.iterdir():
  File "/home/pavel/.pyenv/versions/3.10.2/lib/python3.10/pathlib.py", line 1015, in iterdir
    for name in self._accessor.listdir(self):
PermissionError: [Errno 13] Permission denied: '.tmp/docker'
```

The problem could be resolved on the following lines (by skipping those directories/files which are inaccessible)

https://github.com/lk16/detect-missing-init/blob/master/hook/detect_missing_init.py#L55-L59

But I'm not sure what is the best solution.

BTW this error occurs even though we have specified `--python-folders` which should exclude this inaccessible directory. So it really doesn't make sense it is failing.

**Comment by lk16** [comment]
Hi,

The hook should only be searching through folders that are whitelisted with the `--python-folders` flag when it's used. It currently checks all folders, which is an implementation flaw, leading to this problem. I will fix it.

**Comment by lk16** [comment]
Release [v0.1.6](https://github.com/lk16/detect-missing-init/releases/tag/v0.1.6) fixes this issue. 
Please reopen this issue if you still have problems after updating.
